services:
  postgres-rpe:
    image: postgres:latest
    container_name: postgres-rpe
    environment:
      POSTGRES_DB: soluctiondb
      POSTGRES_USER: soluction
      POSTGRES_PASSWORD: soluction
    ports:
      - "5432:5432"
    networks:
      - rpe

  redis-rpe:
    image: redis:latest
    container_name: redis-rpe
    ports:
      - "6379:6379"
    networks:
      - rpe

  localstack-rpe:
    image: localstack/localstack
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: localstack-rpe
    ports:
      - "4566:4566"
      - "4510:4510"
    environment:
      - SERVICES=sqs  # Ativa o SQS
      - DEFAULT_REGION=us-east-1  # Região padrão
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - LOCALSTACK_HOST=localstack-rpe
    volumes:
      - "./01-init-aws.sh:/etc/localstack/init/ready.d/01-init-aws.sh"
    networks:
      - rpe
    

  product-service:
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres-rpe
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-rpe:5432/soluctiondb
      - SPRING_DATASOURCE_USERNAME=soluction
      - SPRING_DATASOURCE_PASSWORD=soluction
    networks:
      - rpe
  

  card-service:
    container_name: card-service
    build:
      context: ./card-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - redis-rpe
      - postgres-rpe
      - localstack-rpe
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-rpe:5432/soluctiondb
      - SPRING_DATASOURCE_USERNAME=soluction
      - SPRING_DATASOURCE_PASSWORD=soluction
      - SPRING_REDIS_HOST=redis-rpe
      - SPRING_REDIS_PORT=6379
      - SPRING_LOCALSTACK_HOST=http://localstack-rpe:4566
      - SPRING_PRODUCT_SERVICE_URL=http://product-service:8081/product-service
      - SPRING_CARD_SQS_NAME=http://localstack-rpe:4566/000000000000/cards-register
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      - rpe

#  carrier-service:
#    build:
#      context: ./carrier-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - localstack
#      - postgres


volumes:
  localstack_data:
networks:
  rpe:
