services:
  postgres-rpe:
    image: postgres:latest
    environment:
      POSTGRES_DB: soluctiondb
      POSTGRES_USER: soluction
      POSTGRES_PASSWORD: soluction
    ports:
      - "5432:5432"

  redis-rpe:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  localstack-rpe:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510:4510"
    environment:
      - SERVICES=sqs  # Ativa o SQS
      - DEFAULT_REGION=us-east-1  # Região padrão
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres-rpe
  

#  card-service:
#    build:
#      context: ./card-service
#    ports:
#      - "8082:8080"
#    depends_on:
#      - redis
#      - postgres
#      - localstack

#  carrier-service:
#    build:
#      context: ./carrier-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - localstack
#      - postgres


volumes:
  localstack_data: