spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5432/soluctiondb
    username: soluction
    password: soluction
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
server:
  port: 8082
  servlet:
    context-path: /card-service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: test
      secret-key: test
    sqs:
      endpoint: https://localhost.localstack.cloud:4566/000000000000


product-service: http://localhost:8081/product-service
card-sqs-name: https://localhost.localstack.cloud:4566/000000000000/cards-register

